import { Product } from './product.types';

export const PRODUCTS_MOCK: Product[] = [
  // Bucato
  {
    id: 'bucato-1',
    slug: 'detersivo-piatti-limone',
    title: 'Detersivo Piatti Limone',
    categoryIds: ['detersivi-piatti'],
    lineId: 'lavanda',
    images: [{ src: '/images/home/product.png', alt: 'Detersivo Piatti Limone' }],
    volume: '750 ml',
    price: 5.5,
    currency: 'EUR',
    isEco: true,
    isNew: true,
    filters: [],
  },
  {
    id: 'bucato-2',
    slug: 'cura-lavastoviglie',
    title: 'Cura Lavastoviglie Profumata',
    categoryIds: ['cura-lavastoviglie'],
    lineId: 'brezza-marina',
    images: [{ src: '/images/home/product.png', alt: 'Cura Lavastoviglie' }],
    volume: '500 ml',
    price: 6.0,
    currency: 'EUR',
    isEco: false,
    isNew: false,
    filters: [],
  },

  // Cucina
  {
    id: 'cucina-1',
    slug: 'detersivi-bucato',
    title: 'Detersivi Bucato',
    categoryIds: ['detersivi-bucato'],
    lineId: 'limone',
    images: [{ src: '/images/home/product.png', alt: 'Detersivi Bucato' }],
    volume: '750 ml',
    price: 4.5,
    currency: 'EUR',
    isEco: true,
    isNew: false,
    filters: [],
  },
  {
    id: 'cucina-2',
    slug: 'ammorbidenti',
    title: 'Ammorbidenti',
    categoryIds: ['ammorbidenti'],
    lineId: 'fiori-di-campo',
    images: [{ src: '/images/home/product.png', alt: 'Ammorbidenti' }],
    volume: '1000 ml',
    price: 5.0,
    currency: 'EUR',
    isEco: false,
    isNew: true,
    filters: [],
  },

  // Pulizia
  {
    id: 'pulizia-1',
    slug: 'sgrassatori',
    title: 'Sgrassatori',
    categoryIds: ['sgrassatori'],
    lineId: 'agrumi',
    images: [{ src: '/images/home/product.png', alt: 'Sgrassatori' }],
    volume: '500 ml',
    price: 3.5,
    currency: 'EUR',
    isEco: true,
    isNew: false,
    filters: [],
  },
  {
    id: 'pulizia-2',
    slug: 'lavapavimenti',
    title: 'Lavapavimenti',
    categoryIds: ['lavapavimenti'],
    lineId: 'brezza-marina',
    images: [{ src: '/images/home/product.png', alt: 'Lavapavimenti' }],
    volume: '750 ml',
    price: 6.0,
    currency: 'EUR',
    isEco: false,
    isNew: true,
    filters: [],
  },
];
