import { Product } from './product.types';

export const PRODUCTS_MOCK: Product[] = [
  {
    id: 'bucato-1',
    slug: 'detersivo-piatti-limone',
    title: 'Detersivo Piatti Limone',
    categoryIds: ['detersivi-piatti'],
    lineId: 'lavanda',
    images: [{ src: '/images/home/product.png', alt: 'Detersivo Piatti Limone' }],
    volume: '750',
    price: 5.5,
    currency: 'EUR',
    isEco: true,
    isNew: true,
    filters: [],
  },
  {
    id: 'bucato-2',
    slug: 'cura-lavastoviglie',
    title: 'Cura Lavastoviglie Profumata',
    categoryIds: ['cura-lavastoviglie'],
    lineId: 'brezza-marina',
    images: [{ src: '/images/home/product.png', alt: 'Cura Lavastoviglie' }],
    volume: '500',
    price: 6,
    currency: 'EUR',
  },
  {
    id: 'cucina-1',
    slug: 'detersivi-bucato',
    title: 'Detersivi Bucato',
    categoryIds: ['detersivi-bucato'],
    lineId: 'limone',
    images: [{ src: '/images/home/product.png', alt: 'Detersivi Bucato' }],
    volume: '750',
    price: 4.5,
    currency: 'EUR',
  },
  {
    id: 'cucina-2',
    slug: 'ammorbidenti',
    title: 'Ammorbidenti',
    categoryIds: ['ammorbidenti'],
    lineId: 'fiori-di-campo',
    images: [{ src: '/images/home/product.png', alt: 'Ammorbidenti' }],
    volume: '1000',
    price: 5,
    currency: 'EUR',
  },
  {
    id: 'pulizia-1',
    slug: 'sgrassatori',
    title: 'Sgrassatori',
    categoryIds: ['sgrassatori'],
    lineId: 'agrumi-di-sicilia',
    images: [{ src: '/images/home/product.png' }],
    volume: '500',
    price: 3.5,
    currency: 'EUR',
  },
  {
    id: 'pulizia-2',
    slug: 'lavapavimenti',
    title: 'Lavapavimenti',
    categoryIds: ['lavapavimenti'],
    lineId: 'marsiglia',
    images: [{ src: '/images/home/product.png' }],
    volume: '750',
    price: 6,
    currency: 'EUR',
  },
  {
    id: 'bucato-3',
    slug: 'detersivo-piatti-arancia',
    title: 'Detersivo Piatti Arancia',
    categoryIds: ['detersivi-piatti'],
    lineId: 'lavanda',
    images: [{ src: '/images/home/product.png', alt: 'Detersivo Piatti Arancia' }],
    volume: '750',
    price: 5.9,
    currency: 'EUR',
  },
  {
    id: 'cucina-3',
    slug: 'cura-lavastoviglie-aloe',
    title: 'Cura Lavastoviglie Aloe',
    categoryIds: ['cura-lavastoviglie'],
    lineId: 'brezza-marina',
    images: [{ src: '/images/home/product.png', alt: 'Cura Lavastoviglie Aloe' }],
    volume: '500',
    price: 6.5,
    currency: 'EUR',
  },
  {
    id: 'cucina-4',
    slug: 'ammorbidenti-lavanda',
    title: 'Ammorbidenti Lavanda',
    categoryIds: ['ammorbidenti'],
    lineId: 'fiori-di-campo',
    images: [{ src: '/images/home/product.png', alt: 'Ammorbidenti Lavanda' }],
    volume: '1000',
    price: 5.75,
    currency: 'EUR',
  },
  {
    id: 'pulizia-3',
    slug: 'sgrassatori-citronella',
    title: 'Sgrassatori Citronella',
    categoryIds: ['sgrassatori'],
    lineId: 'agrumi-di-sicilia',
    images: [{ src: '/images/home/product.png' }],
    volume: '500',
    price: 3.25,
    currency: 'EUR',
  },
  {
    id: 'pulizia-4',
    slug: 'lavapavimenti-pino',
    title: 'Lavapavimenti Pino',
    categoryIds: ['lavapavimenti'],
    lineId: 'marsiglia',
    images: [{ src: '/images/home/product.png' }],
    volume: '750',
    price: 6.1,
    currency: 'EUR',
  },
  {
    id: 'bucato-4',
    slug: 'detersivo-piatti-limone-eco',
    title: 'Detersivo Piatti Limone Eco',
    categoryIds: ['detersivi-piatti'],
    lineId: 'lavanda',
    images: [{ src: '/images/home/product.png' }],
    volume: '750',
    price: 5.55,
    currency: 'EUR',
  },
  {
    id: 'cucina-5',
    slug: 'detersivi-bucato-fiori',
    title: 'Detersivi Bucato Fiori',
    categoryIds: ['detersivi-bucato'],
    lineId: 'limone',
    images: [{ src: '/images/home/product.png' }],
    volume: '750',
    price: 4.95,
    currency: 'EUR',
  },
  {
    id: 'cucina-6',
    slug: 'ammorbidenti-lino',
    title: 'Ammorbidenti Lino',
    categoryIds: ['ammorbidenti'],
    lineId: 'fiori-di-campo',
    images: [{ src: '/images/home/product.png' }],
    volume: '1000',
    price: 5.0,
    currency: 'EUR',
  },
  {
    id: 'pulizia-5',
    slug: 'sgrassatori-lavanda',
    title: 'Sgrassatori Lavanda',
    categoryIds: ['sgrassatori'],
    lineId: 'agrumi-di-sicilia',
    images: [{ src: '/images/home/product.png' }],
    volume: '500',
    price: 3.0,
    currency: 'EUR',
  },
  {
    id: 'pulizia-6',
    slug: 'lavapavimenti-citronella',
    title: 'Lavapavimenti Citronella',
    categoryIds: ['lavapavimenti'],
    lineId: 'marsiglia',
    images: [{ src: '/images/home/product.png' }],
    volume: '750',
    price: 6.0,
    currency: 'EUR',
  },
  {
    id: 'bucato-5',
    slug: 'detersivo-piatti-arancia-eco',
    title: 'Detersivo Piatti Arancia Eco',
    categoryIds: ['detersivi-piatti'],
    lineId: 'lavanda',
    images: [{ src: '/images/home/product.png' }],
    volume: '750',
    price: 5.0,
    currency: 'EUR',
  },
  {
    id: 'cucina-7',
    slug: 'cura-lavastoviglie-citrus',
    title: 'Cura Lavastoviglie Citrus',
    categoryIds: ['cura-lavastoviglie'],
    lineId: 'brezza-marina',
    images: [{ src: '/images/home/product.png' }],
    volume: '500',
    price: 6.2,
    currency: 'EUR',
  },
  {
    id: 'pulizia-7',
    slug: 'sgrassatori-citro',
    title: 'Sgrassatori Citro',
    categoryIds: ['sgrassatori'],
    lineId: 'agrumi-di-sicilia',
    images: [{ src: '/images/home/product.png' }],
    volume: '500',
    price: 3.75,
    currency: 'EUR',
  },
];
