import { Product } from './product.types';

export const PRODUCTS_MOCK: Product[] = [
  {
    id: 'prod-001',
    sku: 'art.0000001',
    slug: 'detersivo-piatti-limone',
    title: 'Detersivo Piatti Limone',
    description: `Detersivo piatti ricaricabile
Puoi sciogliere rapidamente e facilmente il nostro Detersivo Piatti in Polvere everdrop per ottenere un detersivo liquido. Senza plastica monouso, ma con ingredienti naturali, rende i tuoi piatti e bicchieri splendenti e rimuove anche lo sporco più ostinato e incrostato. Ora con un fresco profumo di limone e gelsomino!
・Pulizia efficace & forte contro il grasso
・100% vegano
・Formula senza microplastiche
・Tensioattivi a base vegetale
・Dermatologicamente testato
・Con inulina dalla radice di cicoria – supporta la barriera cutanea naturale e idrata la pelle
・Con ingredienti facilmente biodegradabili
・Dosaggio semplice grazie al nostro erogatore a pompa
・Confezione facilmente riciclabile nella carta`,
    categoryIds: ['detersivi-piatti'],
    lineId: 'agrumi-di-sicilia',
    images: [{ src: '/images/home/product.png' }],
    variants: [
      { id: 'v1', label: 'ml 500', volume: 500, unit: 'ml', priceModifier: 5.5 },
      { id: 'v2', label: 'ml 1000', volume: 1000, unit: 'ml', priceModifier: 9.0 },
    ],
    weightGrams: 1100,
    price: 5.5,
    currency: 'EUR',
    isBestSeller: true,
  },
  {
    id: 'prod-002',
    sku: 'art.0000002',
    slug: 'detersivo-piatti-limone-gel',
    title: 'Detersivo Piatti Limone Gel',
    description: 'Formula gel concentrata per una pulizia profonda.',
    categoryIds: ['detersivi-piatti'],
    lineId: 'agrumi-di-sicilia',
    images: [{ src: '/images/home/product.png' }],
    variants: [
      { id: 'v1', label: 'ml 500', volume: 500, unit: 'ml', priceModifier: 6.0 },
      { id: 'v2', label: 'ml 1000', volume: 1000, unit: 'ml', priceModifier: 10.5 },
    ],
    weightGrams: 1150,
    price: 6.0,
    currency: 'EUR',
  },
  {
    id: 'prod-003',
    sku: 'art.0000003',
    slug: 'detersivo-lavatrice-lavanda',
    title: 'Detersivo Lavatrice Lavanda',
    description: 'Detersivo delicato e profumato alla lavanda.',
    categoryIds: ['detersivi-lavatrice'],
    lineId: 'lavanda',
    images: [{ src: '/images/home/product.png' }],
    variants: [
      { id: 'v1', label: 'ml 1000', volume: 1000, unit: 'ml', priceModifier: 7.5 },
      { id: 'v2', label: 'ml 2000', volume: 2000, unit: 'ml', priceModifier: 14.0 },
    ],
    weightGrams: 2100,
    price: 7.5,
    currency: 'EUR',
    isBestSeller: true,
  },
  {
    id: 'prod-004',
    sku: 'art.0000004',
    slug: 'detersivo-lavatrice-fiori-di-cotone',
    title: 'Detersivo Lavatrice Fiori di Cotone',
    description: 'Efficace contro le macchie, profumo delicato.',
    categoryIds: ['detersivi-lavatrice'],
    lineId: 'cotone',
    images: [{ src: '/images/home/product.png' }],
    variants: [
      { id: 'v1', label: 'ml 1000', volume: 1000, unit: 'ml', priceModifier: 8.0 },
      { id: 'v2', label: 'ml 2000', volume: 2000, unit: 'ml', priceModifier: 15.0 },
    ],
    weightGrams: 2200,
    price: 8.0,
    currency: 'EUR',
  },
  {
    id: 'prod-005',
    sku: 'art.0000005',
    slug: 'ammorbidente-fiorito',
    title: 'Ammorbidente Fiorito',
    description: 'Morbidezza e profumo intenso.',
    categoryIds: ['ammorbidenti'],
    lineId: 'fiore-di-loto',
    images: [{ src: '/images/home/product.png' }],
    variants: [{ id: 'v1', label: 'ml 750', volume: 750, unit: 'ml', priceModifier: 4.5 }],
    weightGrams: 800,
    price: 4.5,
    currency: 'EUR',
    isBestSeller: true,
  },
  {
    id: 'prod-006',
    sku: 'art.0000006',
    slug: 'detergente-bagno-citronella',
    title: 'Detergente Bagno Citronella',
    description: 'Pulizia e freschezza in un solo gesto.',
    categoryIds: ['detergenti-bagno'],
    lineId: 'citrus',
    images: [{ src: '/images/home/product.png' }],
    variants: [{ id: 'v1', label: 'ml 500', volume: 500, unit: 'ml', priceModifier: 5.0 }],
    weightGrams: 550,
    price: 5.0,
    currency: 'EUR',
  },
  {
    id: 'prod-007',
    sku: 'art.0000007',
    slug: 'sgrassatore-cucina-limone',
    title: 'Sgrassatore Cucina Limone',
    description: 'Rimuove grasso e sporco in cucina con facilità.',
    categoryIds: ['sgrassatori'],
    lineId: 'citrus',
    images: [{ src: '/images/home/product.png' }],
    variants: [{ id: 'v1', label: 'ml 500', volume: 500, unit: 'ml', priceModifier: 5.0 }],
    weightGrams: 600,
    price: 4.0,
    currency: 'EUR',
    isEco: true,
  },
  {
    id: 'prod-008',
    sku: 'art.0000008',
    slug: 'lavapavimenti-legno',
    title: 'Lavapavimenti Legno',
    description: 'Adatto a tutti i tipi di pavimenti in legno.',
    categoryIds: ['lavapavimenti'],
    lineId: 'neutro',
    images: [{ src: '/images/home/product.png' }],
    variants: [{ id: 'v1', label: 'ml 500', volume: 500, unit: 'ml', priceModifier: 5.0 }],
    weightGrams: 1200,
    price: 6.5,
    currency: 'EUR',
    isNew: true,
  },
  {
    id: 'prod-009',
    sku: 'art.0000009',
    slug: 'cura-lavastoviglie-classica',
    title: 'Cura Lavastoviglie Classica',
    description: 'Mantiene la lavastoviglie pulita e profumata.',
    categoryIds: ['cura-lavastoviglie'],
    lineId: 'neutro',
    images: [{ src: '/images/home/product.png' }],
    variants: [{ id: 'v1', label: 'ml 500', volume: 500, unit: 'ml', priceModifier: 5.0 }],
    weightGrams: 500,
    price: 3.5,
    currency: 'EUR',
    isSeasonal: true,
  },
  {
    id: 'prod-010',
    sku: 'art.0000010',
    slug: 'ammorbidente-fiorito-concentrato',
    title: 'Ammorbidente Fiorito Concentrato',
    description: 'Profumo intenso, concentrato e duraturo.',
    categoryIds: ['ammorbidenti'],
    lineId: 'fiore-di-loto',
    images: [{ src: '/images/home/product.png' }],
    variants: [{ id: 'v1', label: 'ml 500', volume: 500, unit: 'ml', priceModifier: 5.0 }],
    weightGrams: 900,
    price: 5.0,
    currency: 'EUR',
    isNew: true,
    isBestSeller: true,
  },
  {
    id: 'prod-011',
    sku: 'art.0000011',
    slug: 'detersivo-bucato-classico',
    title: 'Detersivo Bucato Classico',
    description: 'Efficace contro le macchie più ostinate.',
    categoryIds: ['detersivi-bucato'],
    lineId: 'marsiglia',
    images: [{ src: '/images/home/product.png' }],
    variants: [{ id: 'v1', label: 'ml 500', volume: 500, unit: 'ml', priceModifier: 5.0 }],
    weightGrams: 1500,
    price: 7.0,
    currency: 'EUR',
  },
  {
    id: 'prod-012',
    sku: 'art.0000012',
    slug: 'detersivo-bucato-colorati',
    title: 'Detersivo Bucato Colorati',
    description: 'Protegge i colori e lava efficacemente.',
    categoryIds: ['detersivi-bucato'],
    lineId: 'neutro',
    images: [{ src: '/images/home/product.png' }],
    variants: [{ id: 'v1', label: 'ml 500', volume: 500, unit: 'ml', priceModifier: 5.0 }],
    weightGrams: 1450,
    price: 6.5,
    currency: 'EUR',
    isEco: true,
  },
  {
    id: 'prod-013',
    sku: 'art.0000013',
    slug: 'sgrassatore-igienizzante',
    title: 'Sgrassatore Igienizzante',
    description: 'Rimuove sporco e batteri facilmente.',
    categoryIds: ['sgrassatori'],
    lineId: 'citrus',
    images: [{ src: '/images/home/product.png' }],
    variants: [{ id: 'v1', label: 'ml 500', volume: 500, unit: 'ml', priceModifier: 5.0 }],
    weightGrams: 650,
    price: 5.5,
    currency: 'EUR',
  },
  {
    id: 'prod-014',
    sku: 'art.0000014',
    slug: 'lavapavimenti-pavimento-ceramica',
    title: 'Lavapavimenti Ceramica',
    description: 'Adatto a pavimenti in ceramica e gres.',
    categoryIds: ['lavapavimenti'],
    lineId: 'neutro',
    images: [{ src: '/images/home/product.png' }],
    variants: [{ id: 'v1', label: 'ml 500', volume: 500, unit: 'ml', priceModifier: 5.0 }],
    weightGrams: 1250,
    price: 6.8,
    currency: 'EUR',
    isSeasonal: true,
  },
  {
    id: 'prod-015',
    sku: 'art.0000015',
    slug: 'ammorbidente-lavanda',
    title: 'Ammorbidente Lavanda',
    description: 'Profumo delicato di lavanda.',
    categoryIds: ['ammorbidenti'],
    lineId: 'lavanda',
    images: [{ src: '/images/home/product.png' }],
    variants: [{ id: 'v1', label: 'ml 500', volume: 500, unit: 'ml', priceModifier: 5.0 }],
    weightGrams: 800,
    price: 4.8,
    currency: 'EUR',
    isNew: true,
  },
  {
    id: 'prod-016',
    sku: 'art.0000016',
    slug: 'detersivo-piatti-limone-liquid',
    title: 'Detersivo Piatti Limone Liquid',
    description: 'Formula liquida, facile da usare.',
    categoryIds: ['detersivi-piatti'],
    lineId: 'agrumi-di-sicilia',
    images: [{ src: '/images/home/product.png' }],
    variants: [{ id: 'v1', label: 'ml 500', volume: 500, unit: 'ml', priceModifier: 5.0 }],
    weightGrams: 1120,
    price: 5.8,
    currency: 'EUR',
  },
  {
    id: 'prod-017',
    sku: 'art.0000017',
    slug: 'cura-lavastoviglie-intensiva',
    title: 'Cura Lavastoviglie Intensiva',
    description: 'Mantiene la lavastoviglie pulita in profondità.',
    categoryIds: ['cura-lavastoviglie'],
    lineId: 'marsiglia',
    images: [{ src: '/images/home/product.png' }],
    variants: [{ id: 'v1', label: 'ml 500', volume: 500, unit: 'ml', priceModifier: 5.0 }],
    weightGrams: 520,
    price: 4.2,
    currency: 'EUR',
  },
  {
    id: 'prod-018',
    sku: 'art.0000018',
    slug: 'detergente-bagno-lavanda',
    title: 'Detergente Bagno Lavanda',
    description: 'Profumo rilassante e pulizia profonda.',
    categoryIds: ['detergenti-bagno'],
    lineId: 'lavanda',
    images: [{ src: '/images/home/product.png' }],
    variants: [{ id: 'v1', label: 'ml 500', volume: 500, unit: 'ml', priceModifier: 5.0 }],
    weightGrams: 550,
    price: 5.2,
    currency: 'EUR',
  },
  {
    id: 'prod-019',
    sku: 'art.0000019',
    slug: 'sgrassatore-concentrato',
    title: 'Sgrassatore Concentrato',
    description: 'Rimuove sporco ostinato velocemente.',
    categoryIds: ['sgrassatori'],
    lineId: 'neutro',
    images: [{ src: '/images/home/product.png' }],
    variants: [{ id: 'v1', label: 'ml 1000', volume: 500, unit: 'ml', priceModifier: 5.0 }],
    weightGrams: 700,
    price: 6.0,
    currency: 'EUR',
    isBestSeller: true,
  },
  {
    id: 'prod-020',
    sku: 'art.0000020',
    slug: 'lavapavimenti-pino',
    title: 'Lavapavimenti Pino',
    description: 'Profumo fresco di pino e pulizia profonda.',
    categoryIds: ['lavapavimenti'],
    lineId: 'neutro',
    images: [{ src: '/images/home/product.png' }],
    variants: [{ id: 'v1', label: 'ml 1000', volume: 500, unit: 'ml', priceModifier: 5.0 }],
    weightGrams: 1300,
    price: 7.2,
    currency: 'EUR',
    isSeasonal: true,
  },
  {
    id: 'prod-021',
    sku: 'art.0000021',
    slug: 'detersivo-lavatrice-marsiglia',
    title: 'Detersivo Lavatrice Marsiglia',
    description: 'Detergente classico per bucato perfetto e pulito.',
    categoryIds: ['detersivi-lavatrice'],
    lineId: 'marsiglia',
    images: [{ src: '/images/home/product.png' }],
    variants: [{ id: 'v1', label: 'ml 1000', volume: 500, unit: 'ml', priceModifier: 5.0 }],
    weightGrams: 2000,
    price: 8.0,
    currency: 'EUR',
    isBestSeller: true,
  },
  {
    id: 'prod-022',
    sku: 'art.0000022',
    slug: 'ammorbidente-lavanda-intenso',
    title: 'Ammorbidente Lavanda Intenso',
    description: 'Profumo intenso di lavanda, morbidezza garantita.',
    categoryIds: ['ammorbidenti'],
    lineId: 'lavanda',
    images: [{ src: '/images/home/product.png' }],
    variants: [{ id: 'v1', label: 'ml 1000', volume: 500, unit: 'ml', priceModifier: 5.0 }],
    weightGrams: 850,
    price: 5.0,
    currency: 'EUR',
    isNew: true,
  },
  {
    id: 'prod-023',
    sku: 'art.0000023',
    slug: 'detersivo-piatti-citrus',
    title: 'Detersivo Piatti Citrus',
    description: 'Efficace contro grasso e sporco, profumo agrumato.',
    categoryIds: ['detersivi-piatti'],
    lineId: 'agrumi-di-sicilia',
    images: [{ src: '/images/home/product.png' }],
    variants: [{ id: 'v1', label: 'ml 1000', volume: 500, unit: 'ml', priceModifier: 5.0 }],
    weightGrams: 1100,
    price: 5.5,
    currency: 'EUR',
    isEco: true,
  },
  {
    id: 'prod-024',
    sku: 'art.0000024',
    slug: 'sgrassatore-multipurpose',
    title: 'Sgrassatore Multipurpose',
    description: 'Perfetto per tutte le superfici della cucina.',
    categoryIds: ['sgrassatori'],
    lineId: 'neutro',
    images: [{ src: '/images/home/product.png' }],
    variants: [
      { id: 'v1', label: 'ml 500', volume: 500, unit: 'ml', priceModifier: 5.5 },
      { id: 'v2', label: 'ml 1000', volume: 1000, unit: 'ml', priceModifier: 9.0 },
    ],
    weightGrams: 650,
    price: 5.2,
    currency: 'EUR',
  },
  {
    id: 'prod-025',
    sku: 'art.0000025',
    slug: 'lavapavimenti-cotone',
    title: 'Lavapavimenti Cotone',
    description: 'Pulisce a fondo e lascia un delicato profumo di cotone.',
    categoryIds: ['lavapavimenti'],
    lineId: 'cotone',
    images: [{ src: '/images/home/product.png' }],
    variants: [
      { id: 'v1', label: 'ml 500', volume: 500, unit: 'ml', priceModifier: 5.5 },
      { id: 'v2', label: 'ml 1000', volume: 1000, unit: 'ml', priceModifier: 9.0 },
    ],
    weightGrams: 1250,
    price: 6.5,
    currency: 'EUR',
    isSeasonal: true,
  },
  {
    id: 'prod-026',
    sku: 'art.0000026',
    slug: 'cura-lavastoviglie-deluxe',
    title: 'Cura Lavastoviglie Deluxe',
    description: 'Mantiene la lavastoviglie come nuova.',
    categoryIds: ['cura-lavastoviglie'],
    lineId: 'brezza-marina',
    images: [{ src: '/images/home/product.png' }],
    variants: [
      { id: 'v1', label: 'ml 500', volume: 500, unit: 'ml', priceModifier: 5.5 },
      { id: 'v2', label: 'ml 1000', volume: 1000, unit: 'ml', priceModifier: 9.0 },
    ],
    weightGrams: 500,
    price: 4.5,
    currency: 'EUR',
  },
  {
    id: 'prod-027',
    sku: 'art.0000027',
    slug: 'ammorbidente-fiore-di-loto-concentrato',
    title: 'Ammorbidente Fiore di Loto Concentrato',
    description: 'Concentrazione alta, morbidezza duratura.',
    categoryIds: ['ammorbidenti'],
    lineId: 'fiore-di-loto',
    images: [{ src: '/images/home/product.png' }],
    variants: [
      { id: 'v1', label: 'ml 500', volume: 500, unit: 'ml', priceModifier: 5.5 },
      { id: 'v2', label: 'ml 1000', volume: 1000, unit: 'ml', priceModifier: 9.0 },
    ],
    weightGrams: 900,
    price: 5.2,
    currency: 'EUR',
    isBestSeller: true,
  },
  {
    id: 'prod-028',
    sku: 'art.0000028',
    slug: 'detersivo-bucato-lavanda',
    title: 'Detersivo Bucato Lavanda',
    description: 'Delicato e profumato, ideale per capi colorati.',
    categoryIds: ['detersivi-bucato'],
    lineId: 'lavanda',
    images: [{ src: '/images/home/product.png' }],
    variants: [
      { id: 'v1', label: 'ml 500', volume: 500, unit: 'ml', priceModifier: 5.5 },
      { id: 'v2', label: 'ml 1000', volume: 1000, unit: 'ml', priceModifier: 9.0 },
    ],
    weightGrams: 1500,
    price: 7.2,
    currency: 'EUR',
  },
  {
    id: 'prod-029',
    sku: 'art.0000029',
    slug: 'sgrassatore-cucina-arancia',
    title: 'Sgrassatore Cucina Arancia',
    description: 'Rimuove grasso e sporco con profumo agrumato.',
    categoryIds: ['sgrassatori'],
    lineId: 'agrumi-di-sicilia',
    images: [{ src: '/images/home/product.png' }],
    variants: [
      { id: 'v1', label: 'ml 500', volume: 500, unit: 'ml', priceModifier: 5.5 },
      { id: 'v2', label: 'ml 1000', volume: 1000, unit: 'ml', priceModifier: 9.0 },
    ],
    weightGrams: 600,
    price: 5.0,
    currency: 'EUR',
    isEco: true,
  },
  {
    id: 'prod-030',
    sku: 'art.0000030',
    slug: 'lavapavimenti-citrus',
    title: 'Lavapavimenti Citrus',
    description: 'Profumo fresco di agrumi e pulizia profonda.',
    categoryIds: ['lavapavimenti'],
    lineId: 'agrumi-di-sicilia',
    images: [{ src: '/images/home/product.png' }],
    variants: [
      { id: 'v1', label: 'ml 500', volume: 500, unit: 'ml', priceModifier: 5.5 },
      { id: 'v2', label: 'ml 1000', volume: 1000, unit: 'ml', priceModifier: 9.0 },
    ],
    weightGrams: 1300,
    price: 7.0,
    currency: 'EUR',
    isNew: true,
  },
];
